// Parameters to retrieve data from the Uniswap v3 Oracle
const oracleParameters = {
    baseTimeframe: 'seconds30',
    analysisTimeframe: 'minutes5',
    nPeriodsATR: 20,
    nPeriodsSmoothing: 40,
    initialLookbackMinutes: 60 * 8,
    updateLookbackMinutes: 15,
    maxExtraMinutes: 180 // After retrieving the first set of observations, when
                         // will earliest observations begin to be flushed
}

// ETH Tokens
const tokenSelectionETH = [
    'USDC',
    'ETH',
    'DAI',
    'USDT',
    'WBTC',
    'FRAX',
    'USDM',
    'SWYF',
    'SETH2',
    'AGEUR',
    'BUSD',
    'AVINOC',
    'BIT',
    'FUN',
    'USDD',
    'EURS',
    'APE',
    'FEI',
    'MKR',
    'BTT',
    'CVX',
    'XAUT',
    'UNI',
    'WDOGE',
    'HEX',
    'SHIB',
    'HOPR',
    'ADS',
    'COMP',
    'RPL',
    'FTT',
    'PAX',
    'SIFU',
    'GUSD',
    'XMT',
    'MATIC',
    'LOOKS',
    'LINK',
    'GNO',
    'AAVE',
    'TUSD',
    '1INCH',
    'INST',
    'LCX',
    'BADGER',
    'sUSD',
    'UOS',
    'PEOPLE',
    'ENS',
    'QRDO',
    'WETH',
    // 'BNB',
    // 'VEN',
    // 'KNC',
    // 'LRC',
    // 'RPL',
    // 'DYDX',
    // 'NBU',
    // 'GNBU',
    // 'DPI',
    // 'YFI',
    // 'CRV',
    // 'AMP',
    // 'MANA',
    // 'FTM',
    // 'OHM',
    // 'SUSHI',
    // 'SPELL',
    // 'YGG',
    // 'PERP',
    // 'SNX',
];

// Main quote tokens
const quoteTokensETH = [
    'USDC',
    'USDT',
    'ETH',
    'WETH',
    'DAI'
];

exports.tokenSelectionETH = tokenSelectionETH;
exports.quoteTokensETH = quoteTokensETH;
exports.oracleParameters = oracleParameters;